name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        microservice: [api-gateway, auth-service]

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go 1.20
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20

      - name: Get dependencies
        run: |
          cd ${{ matrix.microservice }}
          go mod download

      - name: Test
        run: |
          cd ${{ matrix.microservice }}
          go test -v ./...